FROM php:7.4-cli

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y libxml2-dev \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install opcache \
    && docker-php-ext-install soap \
    && docker-php-ext-install pdo pdo_mysql

