pipeline{
    agent any
    stages{
        stage("Git Pull"){
            steps{
                git branch: 'dev2',  
                url: 'https://github.com/gbelot2003/appbackend.git'
            }
        }
        stage('Asegurando docker config'){
            steps{
                sh "rm docker-compose.yml"
                sh "cp ./docker/dev/docker-compose.yml ./docker-compose.yml"
            }
        }
        stage("Creando entorno Docker"){
            steps{
                 sh "docker-compose up -d --build"
            }
        }
        stage("Instalando Paquetes Compose"){
            steps{
                sh "docker-compose run --rm composer install"
                sh "docker-compose run --rm artisan config:cache"
            }
        }
        stage("Copiando .env y Corriendo migraciones"){
            steps{
                script {
                    if(fileExists('./src/.env')){
                        echo "========Procesos activos, el archivo Existe========"
                    }else{
                        sh "cp ./src/.env.example ./src/.env"
                        sh "docker-compose run --rm artisan key:generate"
                    }
                }
                
            }
        }
        stage("Migrando y Seeding Tablas"){
            steps{
                sh "docker-compose run --rm artisan migrate:refresh --seed"
                sh "docker-compose run --rm artisan passport:install"
            }
        }
        stage("Ejecutando Pruebas Unitarias"){
            steps{
                sh "docker-compose run --rm artisan test"
            }
        }
    }
    post{
        always{
            echo "========Done========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}
