pipeline{
    agent any
    stages{
        stage("Git Pull"){
            steps{
                git branch: 'dev2',  
                url: 'https://github.com/gbelot2003/appbackend.git'
            }
        }
        stage("Creando entorno Docker"){
            steps{
                sh "docker-compose up -d --build"
            }
        }
        stage("Instalando Paquetes Compose"){
            steps{
                sh "docker-compose exec -T php composer install"
                sh "docker-compose exec -T php php artisan cache:clear"
            }
        }
        stage("Copiando .env y Corriendo migraciones"){
            steps{
                script {
                    if(fileExists('./.env')){
                        echo "========Procesos activos, el archivo Existe========"
                    }else{
                        sh "cp ./.env.example ./.env"
                        sh "docker-compose down"
                        sh "docker-compose -T php php artisan key:generate"
                    }
                }
                
            }
        }
        stage("Agregando link a la carpeta de disco storage"){
            steps{
                script {
                    if(fileExists('./public/storage')){
                        echo "========Procesos activos, el archivo Existe========"
                    } else {
                        sh "cd public && ln -s ../storage/ ./storage"
                    }
                }
                
            }
        }
        stage("Migrando y Seeding Tablas"){
            steps{
                sh "docker-compose exec -T php php artisan migrate:refresh --seed"
                sh "docker-compose exec -T php php artisan passport:install"
            }
        }
        stage("Ejecutando Pruebas Unitarias"){
            steps{
                sh "docker-compose exec -T php php artisan test"
            }
        }
    }
    post{
        always{
            echo "========Done========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}